# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.10.0
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --no-progress
      - name: Format check
        run: yarn prettier:check
      - name: Build Lib
        run: yarn lib:build:prod
      - name: Copy built README & LICENCE into dist
        run: cp README.md LICENSE dist/ngx-hover-opacity
      - name: Build Demo
        run: yarn run demo:build:prod --progress=false --base-href "https://maxime1992.github.io/ngx-hover-opacity/"
      - name: Deploy
        if: contains('refs/heads/master', github.ref)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ngx-hover-opacity-app
      - name: Release
        if: contains('refs/heads/master', github.ref)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
